version: '2'

services:
    zookeeper:
        image: zookeeper:3.5
        container_name: zookeeper
        restart: always
        ports:
            - 2181:2181

    nimbus:
        image: storm:1.1.1
        container_name: nimbus
        command: storm nimbus
            -c storm.local.hostname=192.168.77.3
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 6627:6627

    supervisor:
        image: storm:1.1.1
        container_name: supervisor
        command: storm supervisor
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
        restart: always

    stormui:
        image: storm:1.1.1
        container_name: ui
        command: storm ui
        depends_on:
            - nimbus
        links:
            - nimbus
        restart: always
        ports:
            - 8080:8080
            